### ISSUE TITLE
Font Family

### ISSUE THREAD

**Issue by vivekdhameliya2** [mehdizarepour/text_style_editor#1]
I Can Change Size and But I Can Not Change Font Family ...

**Comment by mehdizarepour** [comment]
Hi @vivekdhameliya2, Thank you for opening this issue.
Could you please prepare an example of your code?

You should add fonts to your `pubspec.yaml` file, like this:

```yaml
fonts:
  - family: Billabong
    fonts:
      - asset: packages/text_style_editor/fonts/Billabong.ttf
  - family: otherFontName
    fonts:
      - asset: packages/text_style_editor/fonts/otherFontName.ttf
```

To see the list of all other supported fonts, [click here](https://github.com/mehdizarepour/text_style_editor/tree/master/lib/fonts)

Let me know if you still have the problem.
